### ISSUE TITLE
[BUG] Errors in Console (Colors)

### ISSUE THREAD

**Issue by s3ppo** [beagle-barks/material_segmented_control#18]
Hi,

i found some errors in console with null_safety 3.0.0, but it seems everything works ??
```
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/material_segmented_control-3.0.0-nullsafety.1/lib/material_segmented_control.dart:166:40: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
    final Color selectedColor = widget.selectedColor ?? Colors.blue;
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/material_segmented_control-3.0.0-nullsafety.1/lib/material_segmented_control.dart:171:42: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.

 - 'Color' is from 'dart:ui'.
    final Color unselectedColor = widget.unselectedColor ?? Colors.white;
                                         ^
```
best regards
Harald

**Comment by IonVillarreal** [comment]
any update on the problem?

**Comment by hyouuu** [comment]
Ping

**Comment by hyouuu** [comment]
@s3ppo @IonVillarreal I made a fork which you can use for now:
```
material_segmented_control:
    git:
      url: https://github.com/hyouuu/material_segmented_control.git
      ref: nullsafety
```
